name: Deploy to Netlify

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --watchAll=false

      - name: Build
        run: npm run build
        
      - name: Rename static file and directory
        run: |
          mkdir -p build/${{ github.event.release.tag_name }}
          mv build/static/js/main.*.js build/${{ github.event.release.tag_name }}/main.js

      - name: Deploy
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          build-dir: build/${{ github.event.release.tag_name }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          github-token: ${{ secrets.TOKEN }}
