name: upload to AWS S3

on:
  release:
    types: [ created ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --watchAll=false

      - name: Build
        run: npm run build
        
      - name: Rename static file and directory
        run: |
          mkdir -p build/${{ github.event.release.tag_name }}
          mv build/static/js/main.*.js build/${{ github.event.release.tag_name }}/main.${{ github.event.release.tag_name }}.js

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build/${{ github.event.release.tag_name }}
